

Prediction if the persun will chutn the job or not from input data using the model

In [9]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model 
import pickle

In [10]:
### LOAD THE ANN TRAINED MODEL , SACLER PICKLE FILE AND ONE HOT PICKLE FILE
model=load_model('model.h5')

## load the encoders and scalers

with open('lable_encoder_gender.pkl','rb') as file:
    lable_encoder_gender = pickle.load(file)

with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo = pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [ ]:
## Input data 

input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [25]:
## encode the input geography value

geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()

geo_encode_df = pd.DataFrame(
    geo_encoded,
    columns=onehot_encoder_geo.get_feature_names_out(['Geography'])
)
geo_encode_df

/Users/lakshitgulia/annclassificationmy/venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [ ]:

input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [29]:
## encode the input gender value

input_df['Gender']= lable_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [32]:
## Conatinate one hot encoded

input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encode_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [33]:
## Scaleing the input data

input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.47154541,  0.90911166,  0.09477172, -0.69844549, -0.29010416,
         0.80510537,  0.63367318,  0.95214374, -0.84805047,  0.98019606,
        -0.57581067, -0.56349184]])

In [34]:
## Predict Churn

prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 119ms/step

array([[0.04344354]], dtype=float32)

In [36]:
prediction_probab= prediction[0][0]
prediction_probab

0.04344354

In [37]:
if prediction_probab > 0.5:
    print('will churn')
else:
    print('will not churn')

will not churn